:toc: left
:toclevels: 5
:toc-title: 目次
:stylesheet: css/style.css
:sectnums:
:sectnumlevels: 5
:table-caption: 表

= エクセル検索拡張ツール

== ツール概要

本ツールはエクセルの検索機能を拡張するためのものである。

== 機能一覧

本ツールに実装されている機能を以下に示す。

.機能一覧
[options="header,autowidth"]
|===
| 機能名 | 内容 

| ブック内検索 | ブック内にあるセル・図形を対象に文字列検索・置換を実施
| ファイル検索 | 特定のディレクトリ内にあるファイルを対象に文字列検索・置換を実施
|===

== 機能詳細

=== 図形内文字列検索

==== ブック内検索

===== 機能概要

ブック内にある図形内の文字列を検索できる。

===== 機能詳細

リボンの「エクセル検索拡張ツール」タブにある「ブック内検索」グループの「検索」ボタンまたは、「検索」スプリットボタンの「ブック内検索」を押下すると検索するための入力フォームが表示される。 +
入力フォームの機能を以下に示す。

. [[shapeSearch1]] 設定内容
+
検索時に必要な設定を以下に示す。
+
[[shapeSearchTable1]]
.検索フォーム入力
[options="heaer,autowidth"]
|===
| 項目 | コントロール | 内容

| 検索文字列 | テキストボックス | 検索したい文字列を入力する。
| 検索場所 | プルダウン | 検索場所を選択する。 +
・シート +
・ブック
| 検索範囲 | プルダウン | 検索対象の範囲を選択する。 +
・すべて +
・セル +
・図形
| 大文字小文字を区別 | チェックボックス | 大文字小文字を区別して検索する。
| 正規表現 | チェックボックス | 正規表現で検索する。
|===
+
. [[shapeSearch2]] 検索実行
+
入力フォームに必要な情報を設定後「すべて検索」ボタンか「次を検索」ボタンを押下することで検索を開始する。
+
.. すべて検索
+
「<<shapeSearchTable1, 検索場所>>」で設定した範囲内で「<<shapeSearchTable1, 検索範囲>>」で設定したものを対象に検索した結果の一覧を入力フォーム下部に出力する。
出力内容は「<<shapeSearch3, 検索結果一覧>>」を参照 +
+
また、検索にヒットした件数をフォーム最下部に表示する。
+
.. 次を検索
+
「<<shapeSearchTable1, 検索場所>>」で設定した範囲内で「<<shapeSearchTable1, 検索範囲>>」で設定したものを対象に検索でヒットしたセル・図形を選択する。
検索にヒットしたものが図形で図形の場所が画面表示外の場合は画面内に収まるように移動する。
複数回実行した場合は他の検索にヒットしたセル・図形に移動する。
+
. [[shapeSearch3]] 検索結果一覧
+
「すべて検索」ボタン押下時、検索結果が1件以上存在する場合は検索結果を入力フォーム下部に一覧として出力される。
出力内容を以下に示す。
+
[[shapeSearchTable2]]
.検索結果一覧出力内容
[options="header, autowidth"]
|===
| 項目 | 内容

| シート | 対象のシート名
| セル/図形名 | 対象のセル・図形名
| 値 | セル・図形内の文字列
|===

==== ブック内置換

===== 機能概要

ブック内にある図形内の文字列を指定した文字列に置換できる。

===== 機能詳細

リボンの「エクセル検索拡張ツール」タブにある「ブック内検索」グループの「検索」スプリットボタンの「ブック内置換」を押下すると置換するための入力フォームが表示される。
入力フォームの機能を以下に示す。

. 設定内容
+
置換フォームに入力する内容は「<<shapeSearch1, 設定内容>>」に加え以下を設定する。
+
[[shapeSearchTable3]]
.フォーム入力
[options="heaer,autowidth"]
|===
| 項目 | コントロール | 内容

| 置換後の文字列 | テキストボックス | 置換したい文字列を入力する。
|===
+
. 置換実行
+
「置換」ボタン押下時、図形を選択している場合は選択中の図形から順に置換する。
+
.. すべて置換
+
「<<shapeSearchTable1, 検索場所>>」で設定した範囲内で「<<shapeSearchTable1, 検索範囲>>」で設定したものを対象に検索でヒットしたすべての文字列を「<<shapeSearchTable3, 置換後の文字列>>」で設定した文字列に置換する。
+
.. 置換
+
「<<shapeSearchTable1, 検索場所>>」で設定した範囲内で「<<shapeSearchTable1, 検索範囲>>」で設定したものを対象に検索でヒットした文字列を「<<shapeSearchTable3, 置換後の文字列>>」で設定した文字列に置換し、選択状態にする。
選択状態にしたものが図形で画面表示外の場合は画面内に収まるように移動する。
+
. 検索実行
+
「<<shapeSearch2, 検索実行>>」を参照

=== ファイル検索

==== ファイル検索

===== 機能概要

指定したディレクトリ内のエクセルファイルにある文字列を検索できる。

===== 機能詳細

リボンの「エクセル検索拡張ツール」タブにある「ファイル検索」ボタンまたは、「ファイル検索」スプリットボタンの「ファイル検索」を押下すると検索するための入力フォームが表示される。 +
また、「ファイル置換」からタブを切り替えても使用が可能。 +
入力フォームの機能を以下に示す。

. [[fileSearch1]] 設定内容
+
検索フォームに入力する内容を下表に示す。
+
[[fileSearchTable1]]
.検索フォーム入力
[options="heaer,autowidth"]
|===
| 項目 | コントロール | 内容

| 検索場所 | テキストボックス | 検索したいディレクトリを入力する。 +
入力規則 +
・絶対パスで入力。 +
・末尾に「\」は不要。
| ディレクトリ設定 | ボタン | 「検索場所」右の「・・・」ボタンを押下するとディレクトリ選択するための画面が表示される。 +
※「検索場所」は手動入力も可能だが、本ボタンからディレクトリを選択することを推奨する。
| 対象ファイル | テキストボックス | 対象ファイル名を記載する。 +
初期値は「xlsx」「xlsm」「xls」が拡張子のファイル全てとなっている。 +
制限事項は「<<limitation1, 対象ファイル>>」参照
| 検索文字列 | テキストボックス | 検索したい文字列を入力する。
| 検索範囲 | ブルダウン | 以下3項目から選択する。 +
・すべて：セル、図形すべての文字列 +
・セル：セル内の文字列 +
・図形：図形内の文字列
| サブディレクトリ検索 | チェックボックス | サブディレクトリも検索する。
| 大文字小文字を区別 | チェックボックス | 大文字小文字を区別して検索する。
| 正規表現 | チェックボックス | 正規表現で検索する。
|===
+
. [[fileSearch2]] 検索実行
+
入力フォームに必要な情報を設定後「検索」ボタンを押下することで検索を開始する。 +
+
.. 検索
+
「<<fileSearchTable1, 検索場所>>」で設定したディレクトリ内にある「<<fileSearchTable1, 対象ファイル>>」で設定したファイルにある文字列を検索する。 +
検索対象は「<<fileSearchTable1, 検索範囲>>」で指定した項目となる。 +
結果は「【ファイル検索】検索結果」シートに出力される。 +
出力内容は「<<fileSearch3, 検索結果>>」参照
+
. [[fileSearch3]] 検索結果
+
「検索」ボタン押下後、「【ファイル検索】検索結果」シートが作成され、検索結果が出力される。 +
出力内容を以下に示す。
+
.検索結果一覧出力内容
[options="header, autowidth"]
|===
| 項目 | 内容

| 検索ディレクトリ | 「<<fileSearchTable1, 検索場所>>」の内容
| 検索キーワード | 「<<fileSearchTable1, 検索文字列>>」の内容
| ファイルパス | 対象のファイルパス
| ファイル名 | 対象のファイル名
| シート名 | 対象のシート名
| セル/図形名 | 検索でヒットした種類により以下が出力される。 +
セル：セルアドレス +
図形：オブジェクト名
| 検索結果 | 対象セル・図形の文字列
|===
+
. 制限事項
+
.. [[limitation1]] 対象ファイル
+
* 「xlsx」「xlsm」「xls」以外の拡張子(「xlsb」も含む)はサポート対象外。 +
一部拡張子はexcelでも開くことが可能だが、動作は補償しない。 +
* 入力規則は以下の通りとなる。
** 複数指定する場合は「;」区切りで指定すること。 +
** 入力文字列は正規表現として認識するため、特殊文字は「\」(エスケープ)すること。(例：拡張子の「.」など) +
** ワイルドカードとして記号は使用できない。

==== ファイル置換

===== 機能概要

指定したディレクトリ内のエクセルファイルにある文字列を指定した文字列に置換できる。

===== 機能詳細

リボンの「エクセル検索拡張ツール」タブにある「ファイル検索」スプリットボタンの「ファイル置換」を押下すると置換するための入力フォームが表示される。 +
また、「ファイル検索」からタブを切り替えても使用が可能。 +
入力フォームの機能を以下に示す。

. [[fileReplace1]] 設定内容
+
置換フォームに入力する内容は「<<fileSearch1, ファイル検索の設定内容>>」に加え以下を設定する。
+
[[fileReplaceTable1]]
.置換フォーム入力
[options="header, autowidth"]
|===
| 項目 | コントロール | 内容

| 置換後の文字列 | テキストボックス | 置換したい文字列を入力する。
|===
+
. [[fileReplace2]] 検索実行
+
.. 検索
+
「<<fileSearch2, 検索実行>>」参照
+
. [[fileReplace3]] 置換実行
+
入力フォームに必要な情報を設定後「置換」ボタンを押下することで置換を開始する。	
+	
* 置換
+
「<<fileSearchTable1, 検索場所>>」で設定したディレクトリ内の「<<fileSearchTable1, 対象ファイル>>」で設定したファイル名にある文字列を検索する。 +
検索対象は「<<fileSearchTable1, 検索範囲>>」で指定した項目となる。 +
検索がヒットした場合は「<<fileReplaceTable1, 置換後の文字列>>」で設定した文字列に置換する。
結果は「【ファイル検索】置換結果」シートに出力される。 +
出力内容は「<<fileReplace4, 置換結果>>」参照
+
. [[fileReplace4]] 置換結果
+
「置換」ボタン押下後、「【ファイル検索】置換結果」シートが作成され、置換結果が出力される。
出力内容は「<<fileSearch3, 検索結果の出力内容>>」に加え以下が出力される。
+
.検索結果一覧出力内容
[options="header, autowidth"]
|===
| 項目 | 内容

| 置換キーワード | 「<<fileReplaceTable1, 置換後の文字列>>」の内容
| 置換結果 | 置換後の対象セル・図形の文字列
|===

=== 共通補助機能

==== 入力フォーム

===== 閉じる

「閉じる」ボタンまたは右上の「×」ボタンを押下することで入力フォームを閉じることが可能。 +
※Escキーでは入力フォームは閉じない。

===== 画面拡大縮小

各フォームは拡大縮小が可能であり、フォーム右上の「□」ボタンを押下することで全画面表示も可能。 +
ただし、最小サイズは決まっているため、最小サイズより縮小はできない。

==== エラー表示

入力フォームの設定不足、設定内容が不正だった場合に以下のメッセージが表示される。

[options="header, autowidth"]
|===
| メッセージ内容 | 条件 | 出力機能

| 検索対象が見つかりません。| 検索文字列が空 +
or +
検索結果が0件 | 図形内文字列検索・置換 +
・ブック内検索 +
・ブック内置換
| 検索文字列がありません。 | 検索文字列が空 | ファイル検索 +
・ファイル検索 +
・ファイル置換
| パスが存在しません。 | 検索場所が空 | ファイル検索 +
・ファイル検索 +
・ファイル置換
|===

また、「ファイル検索・置換」処理中に別のエラーが発生した場合は以下のフォーマットでエラーが表示される。
----
エラーが発生しました。
<クラス名>.<関数名>
<エラー内容>
----

.エラーメッセージの項目
|===
| 項目 | 内容

| <クラス名>.<関数名> | 最後に開始したクラス名、関数名が出力される。 +
エラー原因箇所は該当関数から次の関数呼び出しまでの範囲内となる。 +
(各関数の開始時に設定されるため)
| <エラー内容> | エクセルの標準に設定されている内容が出力される。
|===


==== 実行中制御

===== 途中停止

ファイル検索およびファイル置換実行中に「Esc」キーを押下した際に中断確認のメッセージが表示される。
ただし、「Esc」キーの受け付けは検索処理中・置換処理中のみであり、入力フォームは「Esc」キーで閉じない。